stages:
  prepare:
    cmd: python src/data/make_dataset.py data/raw/UCI_Credit_Card.csv data/processed/
    deps:
      - src/data/make_dataset.py
      - src/features/build_features.py
      - data/raw/UCI_Credit_Card.csv
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  train:
    cmd: python src/models/train.py
    deps:
      - src/models/train.py
      - src/models/pipeline.py
      - data/processed/train.csv
      - data/processed/test.csv
    outs:
      - models/credit_default_model.pkl
    metrics:
      - metrics.json:
          cache: false
